Repository GaProgMan/OwaspHeaders.Core, pull requests merged in 2024-11, with the labels that each got.

#100 Removed Support For .NET 6; Added Support For .NET 9
  .github/workflows/dotnet.yml
  .github/workflows/release.yml
  OwaspHeaders.Core.Example/Controllers/HomeController.cs
  OwaspHeaders.Core.Example/OwaspHeaders.Core.Example.csproj
  OwaspHeaders.Core.Example/Program.cs
  OwaspHeaders.Core.Example/Properties/launchSettings.json
  OwaspHeaders.Core.Example/appsettings.Development.json
  OwaspHeaders.Core.Example/appsettings.json
  OwaspHeaders.Core.Example/packages.lock.json
  OwaspHeaders.Core.Tests/OwaspHeaders.Core.Tests.csproj
  OwaspHeaders.Core.Tests/packages.lock.json
  OwaspHeaders.Core.sln
  README-NuGet.md
  README.md
  changelog.md
  documentation.md
  src/OwaspHeaders.Core.csproj
  src/packages.lock.json
Labels: enhancement, branch required, V9

#110 Fixed URL in config for docs directory
  docs/_config.yml
Labels: enhancement

#111 Initial Customisation of docs theme
  Logo.svg
  docs/_config.yml
  docs/_inlcudes/footer_custom.hml
Labels: enhancement

#119 Very basic documentation files
  docs/Configutation.md
  docs/_config.yml
  docs/index.md
Labels: docs

#121 The max-age value used by the default HSTS header is no longer correct
  OwaspHeaders.Core-Logo-small.png
  OwaspHeaders.Core-Logo.png
  OwaspHeaders.Core.Tests/CustomHeaders/CacheControlHeaderOptionsTests.cs
  OwaspHeaders.Core.Tests/CustomHeaders/ContentSecurityPolicyOptionsTests.cs
  OwaspHeaders.Core.Tests/CustomHeaders/CrossOriginOptionsTests.cs
  OwaspHeaders.Core.Tests/CustomHeaders/ExpectCtOptionsTests.cs
  OwaspHeaders.Core.Tests/CustomHeaders/PermittedCrossDomainPoliciesOptionsTests.cs
  OwaspHeaders.Core.Tests/CustomHeaders/ReferrerPolicyOptionsTests.cs
  OwaspHeaders.Core.Tests/CustomHeaders/SecureHeadersTests.cs
  OwaspHeaders.Core.Tests/CustomHeaders/StrictTransportSecurityOptionsTests.cs
  OwaspHeaders.Core.Tests/CustomHeaders/XContextTypeOptionsTests.cs
  OwaspHeaders.Core.Tests/CustomHeaders/XFrameOptionsTests.cs
  OwaspHeaders.Core.Tests/CustomHeaders/XRemovePoweredByOptions.cs
  OwaspHeaders.Core.Tests/CustomHeaders/XssProtectionOptionTests.cs
  OwaspHeaders.Core.Tests/RegressionTests/CspRegressionTests.cs
  README-NuGet.md
  README.md
  changelog.md
  docs/index.md
  src/Extensions/SecureHeadersMiddlewareBuilder.cs
  src/OwaspHeaders.Core.csproj
  src/OwaspHeadersCore.nuspec
Labels: bug
