Repository GaProgMan/OwaspHeaders.Core, pull requests merged in 2024-12, with the labels that each got.

#125 Feature/docs basic entries
  docs/configuration/Content-Security-Policy.md
  docs/configuration/Strict-Transport-Security.md
  docs/configuration/X-Content-Type-Options.md
  docs/configuration/X-Frame-Options.md
  docs/configuration/X-XSS-Protection.md
Labels: docs

#126 Feature/docs basic entries
  README.md
  docs/configuration/Content-Security-Policy.md
  docs/configuration/Strict-Transport-Security.md
  docs/configuration/X-Content-Type-Options.md
  docs/configuration/X-Frame-Options.md
  docs/configuration/X-XSS-Protection.md
  docs/configuration/index.md
Labels: docs

#127 Feature/docs basic entries
  docs/configuration/Content-Security-Policy.md
  docs/configuration/Strict-Transport-Security.md
  docs/configuration/X-Content-Type-Options.md
  docs/configuration/X-Frame-Options.md
  docs/configuration/X-XSS-Protection.md
Labels: bug, docs

#128 Feature/docs basic entries
  docs/configuration/index.md
Labels: bug, docs

#129 Feature/docs basic entries
  docs/_config.yml
  docs/configuration/index.md
  docs/index.md
Labels: bug, docs

#131 Feature/docs basic entries
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE/ask_a_question.md
  .github/pull_request_template.md
  .github/workflows/dotnet.yml
  .github/workflows/release.yml
  Code-of-Conduct.md
  docs/Code-of-Conduct.md
  docs/Contributing.md
  docs/Minimal-Code-Sample.md
  docs/changelog.md
  docs/index.md
  src/OwaspHeaders.Core.csproj
Labels: docs

#132 Feature/docs basic entries
  .github/ISSUE_TEMPLATE/ask_a_question.md
  .github/ISSUE_TEMPLATE/vulnerability.md
  .github/pull_request_template.md
  SECURITY.md
Labels: docs

#134 Feature/docs basic entries
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/vulnerability.md
  .github/pull_request_template.md
  .github/workflows/release.yml
  README-NuGet.md
  README.md
  SECURITY.md
  docs/Code-of-Conduct.md
  docs/Contributing.md
  docs/configuration/index.md
  docs/index.md
  src/OwaspHeaders.Core.csproj
Labels: docs

#136 Fixed #135 by replacing the incorrect default values for the Cache-Control header with the correct ones.
  src/Extensions/SecureHeadersMiddlewareBuilder.cs
  src/Models/CacheControl.cs
  src/OwaspHeaders.Core.csproj
  tests/OwaspHeaders.Core.Tests/SecureHeadersMiddlewareExtensionTests/SecureHeadersMiddlewareTests.cs
Labels: bug

#137 Feature/configuration docs
  docs/configuration/Cache-Control.md
  docs/configuration/Content-Security-Policy.md
  docs/configuration/Referrer-Policy.md
  docs/configuration/Strict-Transport-Security.md
  docs/configuration/X-Content-Type-Options.md
  docs/configuration/X-Frame-Options.md
  docs/configuration/X-Permitted-Cross-Domain-Policies.md
  docs/configuration/X-XSS-Protection.md
Labels: docs

#138 Feature/docs basic entries
  docs/index.md
Labels: docs

#142 Feature/ignore provided urls
  example/OwaspHeaders.Core.Example/Controllers/HomeController.cs
  example/OwaspHeaders.Core.Example/Program.cs
  src/Extensions/SecureHeadersMiddlewareBuilder.cs
  src/Extensions/SecureHeadersMiddlewareExtensions.cs
  src/Models/SecureHeadersMiddlewareConfiguration.cs
  src/OwaspHeaders.Core.csproj
  src/SecureHeadersMiddleware.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/UrlIgnoreListTests.cs
  tests/OwaspHeaders.Core.Tests/OwaspHeaders.Core.Tests.csproj
  tests/OwaspHeaders.Core.Tests/SecureHeadersMiddlewareExtensionTests/SecureHeadersMiddlewareTests.cs
  tests/OwaspHeaders.Core.Tests/packages.lock.json
Labels: enhancement

#143 Attempted to add manual steps for the CodeQL yml file
  .github/workflows/codeql.yml
Labels: bug

#144 Feature/adding integration tests
  src/Constants.cs
  src/Enums/CspCommandType.cs
  src/Enums/CspSandboxType.cs
  src/Enums/CspUriType.cs
  src/Enums/ReferrerPolicyOptions.cs
  src/Enums/XFrameOptions.cs
  src/Enums/XPermittedCrossDomainOptionValue.cs
  src/Extensions/ContentSecurityPolicyExtensions.cs
  src/Extensions/HttpContextExtensions.cs
  src/Extensions/SecureHeadersMiddlewareBuilder.cs
  src/Extensions/SecureHeadersMiddlewareExtensions.cs
  src/Extensions/StringBuilderExtensions.cs
  src/Helpers/ArgumentExceptionHelper.cs
  src/Helpers/ContentSecurityPolicyHelpers.cs
  src/Models/CacheControl.cs
  src/Models/ContentSecurityPolicyConfiguration.cs
  src/Models/ContentSecurityPolicyElement.cs
  src/Models/ContentSecurityPolicyExtensions.cs
  src/Models/ContentSecurityPolicyReportOnlyConfiguration.cs
  src/Models/ContentSecurityPolicySandBox.cs
  src/Models/CrossOriginResourcePolicy.cs
  src/Models/ExpectCt.cs
  src/Models/HstsConfiguration.cs
  src/Models/IConfigurationBase.cs
  src/Models/PermittedCrossDomainPolicyConfiguration.cs
  src/Models/ReferrerPolicy.cs
  src/Models/SecureHeadersMiddlewareConfiguration.cs
  src/Models/XFrameOptionsConfiguration.cs
  src/Models/XssConfiguration.cs
  src/OwaspHeaders.Core.csproj
  src/SecureHeadersMiddleware.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/CacheControlHeaderOptionsTests.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/ContentSecurityPolicyOptionsTests.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/CrossOriginOptionsTests.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/DefaultSecureHeadersIntegrationTests.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/ExpectCtOptionsTests.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/GlobalUsings.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/PermittedCrossDomainPoliciesOptionsTests.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/ReferrerPolicyOptionsTests.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/SecureHeadersTests.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/StrictTransportSecurityOptionsTests.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/UrlIgnoreListTests.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/XContextTypeOptionsTests.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/XFrameOptionsTests.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/XssProtectionOptionTests.cs
  tests/OwaspHeaders.Core.Tests/HttpContextExtensionsTests/TryAdd.cs
  tests/OwaspHeaders.Core.Tests/HttpContextExtensionsTests/TryRemove.cs
  tests/OwaspHeaders.Core.Tests/RegressionTests/CspRegressionTests.cs
  tests/OwaspHeaders.Core.Tests/SecureHeadersMiddlewareExtensionTests/SecureHeadersMiddlewareTests.cs
  tests/OwaspHeaders.Core.Tests/StringBuilderExtensionsTests/TrimEndTests.cs
Labels: enhancement

#147 Fix .NET SDK mismatches in actions
  .github/workflows/codeql.yml
  .github/workflows/dotnet.yml
  .github/workflows/release.yml
  src/OwaspHeaders.Core.csproj
Labels: bug

#148 Add Attestations to build and release workflow
  .github/workflows/dotnet.yml
  .github/workflows/release.yml
  README-NuGet.md
  README.md
  changelog.md
  docs/Code-of-Conduct.md
  docs/Contributing.md
  docs/Minimal-Code-Sample.md
  docs/assets/images/attestations/artifacts.jpg
  docs/assets/images/attestations/created.jpg
  docs/attestations.md
  docs/changelog.md
  docs/configuration/index.md
  src/OwaspHeaders.Core.csproj
Labels: enhancement

#150 Updated docs for attestations on release
  docs/assets/images/attestations/pr-created.jpg
  docs/assets/images/attestations/release-created.jpg
  docs/attestations.md
Labels: enhancement

#151 Fix for images not displaying in attestations docs
  docs/attestations.md
Labels: bug

#152 Header Caching
  src/Constants.cs
  src/OwaspHeaders.Core.csproj
  src/SecureHeadersMiddleware.cs
Labels: enhancement

#154 Bugfix/editorconfig bug
  changelog.md
  docs/changelog.md
  src/OwaspHeaders.Core.csproj
  src/SecureHeadersMiddleware.cs
Labels: bug

#155 feature/frozen-dictionary
  src/OwaspHeaders.Core.csproj
  src/SecureHeadersMiddleware.cs
Labels: enhancement

#156 feature/list-of-headers-in-docs
  docs/index.md
Labels: docs

#157 Bugfix/typos
  src/Models/PermittedCrossDomainPolicyConfiguration.cs
  src/Models/XFrameOptionsConfiguration.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/DefaultSecureHeadersIntegrationTests.cs
  tests/OwaspHeaders.Core.Tests/SecureHeadersMiddlewareExtensionTests/SecureHeadersMiddlewareTests.cs
Labels: bug

#158 feature/list-of-headers-in-docs
  docs/index.md
Labels: docs

#160 Feature/cross origin opener policy
  docs/configuration/Cache-Control.md
  docs/configuration/Cross-Origin-Opener-Policy.md
  docs/configuration/Cross-Origin-Resource-Policy.md
  docs/configuration/X-XSS-Protection.md
  docs/index.md
  src/Constants.cs
  src/Extensions/SecureHeadersMiddlewareBuilder.cs
  src/Extensions/SecureHeadersMiddlewareExtensions.cs
  src/Models/CrossOriginOpenerPolicy.cs
  src/Models/CrossOriginResourcePolicy.cs
  src/Models/SecureHeadersMiddlewareConfiguration.cs
  src/OwaspHeaders.Core.csproj
  src/SecureHeadersMiddleware.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/CrossOriginOptionsTests.cs
  tests/OwaspHeaders.Core.Tests/SecureHeadersMiddlewareExtensionTests/SecureHeadersMiddlewareTests.cs
Labels: enhancement

#162 Bugfix/docs links
  docs/index.md
Labels: docs

#163 Fix readme: Http header syntax highlighting
  README-NuGet.md
  README.md
Labels: docs

#164 Feature/cross origin embedder policy
  README-NuGet.md
  README.md
  changelog.md
  docs/changelog.md
  docs/configuration/Cross-Origin-Embedder-Policy.md
  docs/configuration/Cross-Origin-Opener-Policy.md
  docs/index.md
  src/Constants.cs
  src/Extensions/SecureHeadersMiddlewareBuilder.cs
  src/Extensions/SecureHeadersMiddlewareExtensions.cs
  src/Guards/BoolValueGuardClausesArgumentException.cs
  src/Helpers/ArgumentExceptionHelper.cs
  src/Models/CrossOriginEmbedderPolicy.cs
  src/Models/SecureHeadersMiddlewareConfiguration.cs
  src/OwaspHeaders.Core.csproj
  src/SecureHeadersMiddleware.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/CrossOriginOptionsTests.cs
  tests/OwaspHeaders.Core.Tests/GuardClauses/HeaderValueGuardClausesStringValues.cs
Labels: enhancement

#165 Feature/cross origin embedder policy
  docs/configuration/Cross-Origin-Embedder-Policy.md
  docs/configuration/index.md
  docs/index.md
Labels: docs

#166 Fixed some very small docs issues
  docs/index.md
Labels: docs

#167 Bugfix/coep default header value
  README-NuGet.md
  README.md
  src/Models/CrossOriginEmbedderPolicy.cs
  src/OwaspHeaders.Core.csproj
  src/SecureHeadersMiddleware.cs
  tests/OwaspHeaders.Core.Tests/CustomHeaders/CrossOriginOptionsTests.cs
Labels: bug
